
package service.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import types.ListOfUsers;
import types.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://endpoint.service/")
@XmlSeeAlso({
    service.endpoint.ObjectFactory.class,
    types.ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @return
     *     returns types.ListOfUsers
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.GetAllUsersResponse")
    @Action(input = "http://endpoint.service/UserService/getAllUsersRequest", output = "http://endpoint.service/UserService/getAllUsersResponse")
    public ListOfUsers getAllUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfUsers
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.DeleteUserResponse")
    @Action(input = "http://endpoint.service/UserService/deleteUserRequest", output = "http://endpoint.service/UserService/deleteUserResponse")
    public ListOfUsers deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns types.ListOfUsers
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setNewUser", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewUser")
    @ResponseWrapper(localName = "setNewUserResponse", targetNamespace = "http://endpoint.service/", className = "service.endpoint.SetNewUserResponse")
    @Action(input = "http://endpoint.service/UserService/setNewUserRequest", output = "http://endpoint.service/UserService/setNewUserResponse")
    public ListOfUsers setNewUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
